export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_FAILED_INGREDIENTS = 'FETCH_FAILED_INGREDIENTS';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const SUCCES_TO_SERVER = 'SUCCES_TO_SERVER';
export const FAILURE_FROM_SERVER = 'FAILURE_FROM_SERVER';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const ORDER_RETRIEVE_FROM_SERVER = 'ORDER_RETRIEVE_FROM_SERVER';
export const ORDER_RETRIEVE_FROM_SERVER_FAILED = 'ORDER_RETRIEVE_FROM_SERVER_FAILED'

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAIL ='AUTH_FAIL';
export const AUTH_LOGGOUT = 'AUTH_LOGGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
